# Configure the build matrix
env:
  matrix:
  - TEST=validation
  - TEST=pgsql
  - TEST=mysql
  global:
  - secure: "CthDzj2Id63UaWnBJIgOn3a6XM/Ztt0rttGeaaFhD+M/t33l0J+PGd0BFOv9ilFEUNugE5vbLl7LuVLJQx9dY+r3MpO/dwWQ1detvpwVZ1HyhGe6BX8rs8Y26Q7WDUDMfB33vBYAQ72qyl/099KPmWu5rgmSnEXJY9YYl9fNJMg="
language: php
php:
  - 5.3
python:
  - 3.3
addons:
  postgresql: "9.1"
git:
  # We have to init submodules ourselves to make it recursive
  submodules: false

before_install:
  # Start submodules
  - ./tools/startSubmodulesTRAVIS.sh

  # Install composer dependencies
  - cd lib/pkp && composer update && cd ../..

  # Configure the webserver
  - if [[ "$TEST" != "validation" ]]; then ./lib/pkp/tools/travis/prepare-webserver.sh; fi

  # Start xvfb
  - if [[ "$TEST" != "validation" ]]; then ./lib/pkp/tools/travis/start-xvfb.sh; fi

  # Start Selenium
  - if [[ "$TEST" != "validation" ]]; then ./lib/pkp/tools/travis/start-selenium.sh; fi

  # Prepare code coverage
  - if [[ "$TEST" == "mysql" ]]; then ./lib/pkp/tools/travis/prepare-code-coverage.sh; fi

  # Install the JS linter
  - if [[ "$TEST" == "validation" ]]; then ./lib/pkp/tools/travis/install-linter.sh; fi

  # Sleep and output our logs, to avoid hanging build with no access to
  # logs. This is useful for debugging but too verbose to leave enabled.
  # - (sleep 590; cat access.log; cat error.log; cat xvfb-output; cat selenium-output; cat ./lib/pkp/tests/results/error.log) &

script:
  - if [[ "$TEST" != "validation" ]]; then ./lib/pkp/tools/travis/run-tests.sh; fi
  - if [[ "$TEST" == "validation" ]]; then ./lib/pkp/tools/travis/validate-xml.sh && ./lib/pkp/tools/buildjs.sh; fi

after_script:
  # Merge the coverage reports into one HTML report and upload to http://pkp.sfu.ca/test-coverage 
  - if [[ "$TEST" == "mysql" ]]; then ./lib/pkp/tools/travis/post-code-coverage.sh; fi
  # Print logs and outputs for debugging.
  # - cat access.log
  - cat error.log
  # - cat xvfb-output
  # - cat selenium-output
  - cat ./lib/pkp/tests/results/error.log
  - for f in lib/pkp/tests/results/*.png; do echo ============== START ${f} ================== ; cat $f | base64 ; echo ============== END ${f} ================== ; done
