language: php
php:
  - 5.3
python:
  - 3.3

before_install:
  # Start apache and configure a virtual host.
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl
  - sudo sed -i -e "s,/var/www,$(pwd)/,g" /etc/apache2/sites-available/default 
  - sudo sed -i -e "s,\${APACHE_LOG_DIR},$(pwd),g" /etc/apache2/sites-available/default  
  - sudo /etc/init.d/apache2 restart
  
  # Install php unit selenium extension.
  - pear channel-discover pear.phpunit.de
  - pear install phpunit/PHPUnit_Selenium

  # Xvfb requirements.
  - sudo apt-get install -y x11-xkb-utils
  # Add fonts.
  - sudo apt-get install -y xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic
  - sudo apt-get install -y defoma x-ttcidfont-conf cabextract ttf-mscorefonts-installer
  - sudo dpkg-reconfigure --default-priority x-ttcidfont-conf
  - mkfontdir
  # Start Virtual Framebuffer to imitate a monitor.
  - sudo Xvfb :10 -ac > xvfb-output & 
  - export DISPLAY=:10
  - sleep 3 # Give xvfb time to start.

  # Start selenium server.
  - wget http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar
  - nohup java -jar selenium-server-standalone-2.41.0.jar -browserSessionReuse -debug > selenium-output & 
  - sleep 3 # Give selenium server time to start.

  # Install the test database.
  - mysql -u root -e 'create database ojs'
  - mysql -u root ojs < tests/functional/testserver.sql

  # Files dependency.
  - mv config.TRAVIS.inc.php config.inc.php

  # Make sure permissions are ok.
  - sudo chown -R travis:www-data .

  # Install python, linter, closure compiler stuff
  # - sudo apt-get install python-dev
  # - sudo apt-get install python-setuptools
  # - sudo apt-get install python-nose
  - sudo easy_install "http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz"
  - mkdir ~/bin
  - wget -O compiler.zip "https://closure-compiler.googlecode.com/files/compiler-20120917.zip"
  - unzip compiler.zip compiler.jar
  - mv compiler.jar ~/bin
  - wget "http://jslint4java.googlecode.com/files/jslint4java-2.0.2-dist.zip"
  - unzip jslint4java-2.0.2-dist.zip
  - mv jslint4java-2.0.2/jslint4java-2.0.2.jar ~/bin/jslint4java.jar

script:
  - ./lib/pkp/tools/runAllTests.sh -Ccf
  - ./lib/pkp/tools/validatexml.sh
  - ./lib/pkp/tools/buildjs.sh

after_script: 
  # Print logs and outputs for debugging.
  - cat access.log
  - cat error.log
  - cat xvfb-output
  - cat selenium-output
  - cat ./lib/pkp/tests/results/error.log
